version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - auth-service
      - blog-service
      - comment-service
      - profile-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/auth
    depends_on:
      - mongo

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/blog
    depends_on:
      - mongo

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
      - PORT=6000
      - MONGO_URI=mongodb://mongo:27017/comment
    depends_on:
      - mongo

  profile-service:
    build:
      context: ./profile-service
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
      - MONGO_URI=mongodb://mongo:27017/profile
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: